# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170726_0814'),
        ('projects', '0002_auto_20170726_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date published',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 26, 8, 14, 30, 110412)),
        ),
        migrations.AddField(
            model_name='project',
            name='is_https',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
