# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170726_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date published',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 26, 8, 14, 52, 554578)),
        ),
    ]
