# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 08:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170727_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date published',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 4, 27, 6, 908982)),
        ),
    ]
