# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20170727_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date published',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 3, 20, 29, 968254)),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
