# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 07:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170728_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date published',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 3, 27, 2, 675444)),
        ),
    ]
