# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20170728_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date published',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 3, 44, 34, 864191)),
        ),
    ]
