# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 07:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20170728_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date published',
        ),
        migrations.AddField(
            model_name='project',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 3, 49, 44, 877830)),
        ),
    ]
