# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 02:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_remove_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 29, 2, 56, 15, 483347, tzinfo=utc)),
        ),
    ]
