# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
