# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainsite', '0002_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=30)),
                ('link_url', models.URLField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
