# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20170727_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(),
        ),
    ]
